# Generated by Django 4.2 on 2023-04-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0001_initial"),
        ("snippets", "0001_initial"),
        ("accounts", "0004_snippetassignment_schemaassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=256)),
                ("value", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="schemas",
            field=models.ManyToManyField(
                through="accounts.SchemaAssignment", to="schema.schema"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="snippets",
            field=models.ManyToManyField(
                through="accounts.SnippetAssignment", to="snippets.snippet"
            ),
        ),
        migrations.CreateModel(
            name="SecretAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_view_secret", models.BooleanField(default=True)),
                ("can_edit_secret", models.BooleanField(default=True)),
                ("begin_date", models.DateTimeField(auto_now_add=True)),
                (
                    "secret",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.secret",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="secrets",
            field=models.ManyToManyField(
                through="accounts.SecretAssignment", to="accounts.secret"
            ),
        ),
    ]
