# Generated by Django 4.2 on 2023-04-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="column",
                to="schema.table",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="uri",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="schema",
            name="datasource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="schema",
                to="schema.datasource",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="table",
                to="schema.schema",
            ),
        ),
    ]
